@landingUrl = http://localhost:3000/
@baseUrl = http://localhost:3000/api
@userId = 1

### abriendo la landing page
GET {{landingUrl}}

### obtener todos los usuarios
GET http://localhost:3000/users/all

### registrar a un nuevo usuario
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name" : "Dan",
    "surname" : "Goldman",
    "email" : "goldmandan89@gmail.com",
    "phone" : "1138021709",
    "password" : "osia"
}

### login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "goldmandan8@gmail.com",
    "password" : "aaa"
}

### reestablecer la contraseña
PUT http://localhost:3000/users/password-reset
Content-Type: application/json

{
    "email" : "goldmandan8@gmail.com",
    "newPassword" : "osia"
}

### borrar un usuario
DELETE http://localhost:3000/users
Content-Type: application/json

{
    "email" : ""
}

### agregando una imagen
POST {{baseUrl}}/radiographies/add-image
Content-Type: application/json

{
    "image" : "./images/hands.jpg",
    "bodyPart" : "Brazo",
    "userId" : "1"
}

### obteniendo una radiografia por id del usuario
GET {{baseUrl}}/radiographies/{{userId}}

### borrando una radiografia
DELETE {{baseUrl}}/radiographies/delete-image
Content-Type: application/json

{
    "image_route" : "imagen" 
}

### testing sessions
GET http://localhost:3000/home


### login using sessions
POST http://localhost:3000/login
Content-Type: application/json

{
    "email" : "dan@gmail.com",
    "password" : "secret"
}

