@baseUrl = http://localhost:3000
@userId = 1

### abriendo la landing page
GET {{baseUrl}}

### registrar a un nuevo usuario
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name" : "Dan",
    "surname" : "Goldman",
    "email" : "goldmandan8@gmail.com",
    "phone" : "1138021709",
    "password" : "osia"
}

### login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email" : "goldmandan8@gmail.com",
    "password" : "osia"
}

### obtener todos los usuarios
GET {{baseUrl}}/users/all

### reestablecer la contraseña
PUT {{baseUrl}}/users/password-reset
Content-Type: application/json

{
    "email" : "goldmandan8@gmail.com",
    "newPassword" : "osia"
}

### borrar un usuario
DELETE {{baseUrl}}/users
Content-Type: application/json

{
    "email" : ""
}

### agregar una radiografia
POST {{baseUrl}}/radiography/add
Content-Type: application/json

{
    "imageRoute" : "./images/hands.jpg",
    "bodyPart" : "Brazo",
    "userId" : "1"
}

### obteniendo las radiografias de un usuario
GET {{baseUrl}}/radiography
Content-Type: application/json

{
    "userId" : "1"
}

### borrando una radiografia
DELETE {{baseUrl}}/radiography/delete
Content-Type: application/json

{
    "imageRoute" : "./images/hands.jpg"
}

### testing sessions
GET http://localhost:3000/home


### login using sessions
POST http://localhost:3000/login
Content-Type: application/json

{
    "email" : "dan@gmail.com",
    "password" : "secret"
}
