@landingUrl = http://localhost:3000/
@baseUrl = http://localhost:3000/api
@userId = 1

### abriendo la landing page
GET {{landingUrl}}

### obteniendo todos los usuarios
GET {{baseUrl}}/users/get-all

### obteniendo un usuario por id
GET {{baseUrl}}/users/{{userId}}

### modificando un usuario por id
PUT {{baseUrl}}/users/name-reset/{{userId}}
Content-type: application/json

{
    "name" : "Dan"
}

### borrando un usuario
DELETE {{baseUrl}}/users/{{userId}}

### registrando un usuario
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name" : "Ian",
    "surname" : "Polonuer",
    "email" : "ipolonuer@gmail.com",
    "phone" : "-",
    "password" : "polo"
}

### login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email" : "goldmandan8@gmail.com",
    "password" : "osia"
}

### modificando la contraseña
PUT {{baseUrl}}/users/password-reset
Content-Type: application/json

{
    "email" : "goldmandan8@gmail.com",
    "password" : "osia"
}

### agregando una imagen
POST {{baseUrl}}/radiography/add-image
Content-Type: application/json

{
    "image" : "./images/hands.jpg",
    "bodyPart" : "Brazo",
    "userId" : "1"
}

### obteniendo una radiografia por id del usuario
GET {{baseUrl}}/radiography/{{userId}}
Content-Type: application/json

### borrando una radiografia
DELETE {{baseUrl}}/radiography/delete-image
Content-Type: application/json

{
    "image" : "imagen" 
}

