@landingUrl = http://localhost:3000/
@baseUrl = http://localhost:3000/api
@userId = 1

### abriendo la landing page
GET {{landingUrl}}

### obteniendo todos los usuarios
GET {{baseUrl}}/users/all

### obteniendo un usuario por id
GET {{baseUrl}}/users/{{userId}}

### modificando un usuario por id
PUT {{baseUrl}}/users/name-reset
Content-type: application/json

{
    "email" : "goldmandan8@gmail.com",
    "name" : "Dan"
}

### modificando la contraseña
PUT {{baseUrl}}/users/password-reset
Content-Type: application/json

{
    "email" : "goldmandan8@gmail.com",
    "password" : "dan"
}

### registrando un usuario
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name" : "",
    "surname" : "",
    "email" : "",
    "phone" : "",
    "password" : ""
}

### login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email" : "goldmandan8@gmail.com",
    "password" : "dan"
}

### borrando un usuario
DELETE {{baseUrl}}/users/{{userId}}

### agregando una imagen
POST {{baseUrl}}/radiographies/add-image
Content-Type: application/json

{
    "image" : "./images/hands.jpg",
    "bodyPart" : "Brazo",
    "userId" : "1"
}

### obteniendo una radiografia por id del usuario
GET {{baseUrl}}/radiographies/{{userId}}

### borrando una radiografia
DELETE {{baseUrl}}/radiographies/delete-image
Content-Type: application/json

{
    "image" : "imagen" 
}

### obteniendo las tablas
GET {{baseUrl}}/radiographies/tables


