@baseUrl = http://localhost:3000/api
@userId = 1

### obteniendo todos los usuarios
GET {{baseUrl}}/users/

### obteniendo un usuario por id
GET {{baseUrl}}/users/{{userId}}

### creando un usuario
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "name" : "",
    "surname" : "",
    "email" : "",
    "phone" : "",
    "password" : ""
}

### modificando un usuario por id
PUT {{baseUrl}}/users/{{userId}}
Content-type: application/json

{
    "name" : "Dan"
}

### borrando un usuario
DELETE {{baseUrl}}/users/{{userId}}

### show usersLogin
GET {{baseUrl}}/usersLogin

### create usersLogin
POST {{baseUrl}}/usersLogin
Content-Type: application/json

{
    "name": "Dan",
    "password" : "password" 
}

### login
POST {{baseUrl}}/usersLogin/login
Content-Type: application/json

{
    "name": "Dan",
    "password" : "passsword" 
}