@baseUrl = http://localhost:3000/api
@userId = 25

### obteniendo todos los usuarios
GET {{baseUrl}}/users/

### obteniendo un usuario por id
GET {{baseUrl}}/users/{{userId}}

### modificando un usuario por id
PUT {{baseUrl}}/users/{{userId}}
Content-type: application/json

{
    "name" : "Dan"
}

### borrando un usuario
DELETE {{baseUrl}}/users/{{userId}}

### registrando un usuario
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name" : "",
    "surname" : "",
    "email" : "",
    "phone" : "",
    "password" : ""
}

### login
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email" : "email",
    "password" : "password"
}