@baseUrl = http://localhost:3000/api
@userId = 4

### obteniendo todos los usuarios
GET {{baseUrl}}/users/

### obteniendo un usuario por id
GET {{baseUrl}}/users/{{userId}}

### creando un usuario
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "name" : "Nacho"
}

### modificando un usuario por id
PUT {{baseUrl}}/users/{{userId}}
Content-type: application/json

{
    "name" : "Dan232"
}

### borrando un usuario
DELETE {{baseUrl}}/users/{{userId}}